#!/bin/bash

# Haven Design & Build - Website Launch Checklist
# Run through this checklist before going live

echo "🚀 Haven Design & Build - Pre-Launch Checklist"
echo "=============================================="
echo ""

# Color codes
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Utility function
check_item() {
    read -p "$1 (y/n)? " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${GREEN}✓ DONE${NC}"
    else
        echo -e "${RED}✗ PENDING${NC}"
    fi
    echo ""
}

echo "📋 CONTENT & CUSTOMIZATION"
echo "========================="
check_item "All text and descriptions updated with your business info"
check_item "Company logo/branding added"
check_item "Project photos uploaded and URLs updated"
check_item "Testimonials updated with real customer quotes"
check_item "Contact email and phone verified"
check_item "Social media links updated"
check_item "All typos and grammar checked"

echo ""
echo "📧 EMAIL CONFIGURATION"
echo "====================="
check_item "Email service chosen (Formspree/EmailJS/SendGrid)"
check_item "Email service account created and verified"
check_item "Email service API key/form ID obtained"
check_item "Email service integrated into js/app.js"
check_item "Test email form submission successful"
check_item "Test email received in inbox"
check_item "Backup email configured"

echo ""
echo "💳 STRIPE PAYMENT SETUP"
echo "======================"
check_item "Stripe account created"
check_item "Stripe account verified"
check_item "Payment product created in Stripe"
check_item "Stripe publishable key obtained"
check_item "Payment link created in Stripe"
check_item "Payment link added to website"
check_item "Test payment completed successfully"

echo ""
echo "📅 CALENDLY INTEGRATION"
echo "======================"
check_item "Calendly account created"
check_item "Calendar connected (Google/Outlook/etc)"
check_item "Availability configured"
check_item "Event type created"
check_item "Calendly URL obtained"
check_item "Calendly URL added to website"
check_item "Calendly embed tested in browser"

echo ""
echo "🌐 DOMAIN & HOSTING"
echo "==================="
check_item "Domain registered"
check_item "Hosting provider chosen"
check_item "Hosting account created"
check_item "Domain nameservers configured"
check_item "SSL certificate installed"
check_item "HTTPS working (green lock icon)"

echo ""
echo "🧪 TESTING - FUNCTIONALITY"
echo "========================="
check_item "Home page loads completely"
check_item "Services page displays all 4 services"
check_item "Inquire page form loads"
check_item "Payments page displays payment options"
check_item "Navigation between all pages works"
check_item "All links are not broken"
check_item "All images display correctly"
check_item "All buttons are clickable"

echo ""
echo "🧪 TESTING - FORMS"
echo "=================="
check_item "Contact form validation works"
check_item "Contact form accepts all required fields"
check_item "Contact form rejects invalid emails"
check_item "Contact form submission successful"
check_item "Submitted form data received in email"
check_item "Form clears after submission"
check_item "Error messages display correctly"

echo ""
echo "🧪 TESTING - MOBILE"
echo "==================="
check_item "Website works on iPhone"
check_item "Website works on Android"
check_item "Website works on iPad"
check_item "Hamburger menu appears on mobile"
check_item "Hamburger menu opens/closes"
check_item "Text is readable on mobile"
check_item "Images scale properly on mobile"
check_item "Forms work on mobile"
check_item "Payment link works on mobile"
check_item "Calendly loads on mobile"

echo ""
echo "🧪 TESTING - DESKTOP"
echo "===================="
check_item "Website works on Chrome"
check_item "Website works on Firefox"
check_item "Website works on Safari"
check_item "Website responsive at 1920px width"
check_item "Website responsive at 1440px width"
check_item "Website responsive at 768px width"
check_item "Website responsive at 480px width"

echo ""
echo "📊 ANALYTICS & MONITORING"
echo "========================="
check_item "Google Analytics account created"
check_item "Measurement ID obtained"
check_item "Analytics tracking code added"
check_item "Analytics data appearing in dashboard"
check_item "Uptime monitoring configured"
check_item "Downtime alerts enabled"
check_item "Form submission alerts configured"

echo ""
echo "🔐 SECURITY & COMPLIANCE"
echo "========================"
check_item "SSL certificate active (HTTPS)"
check_item "No browser console errors"
check_item "No console warnings"
check_item "Stripe keys not exposed in code"
check_item "Email credentials secured"
check_item "Privacy policy page reviewed"
check_item "Terms of service page reviewed"
check_item "Password strength verified for all services"

echo ""
echo "📱 CROSS-BROWSER TESTING"
echo "========================"
check_item "Desktop - Chrome 90+"
check_item "Desktop - Firefox 88+"
check_item "Desktop - Safari 14+"
check_item "Desktop - Edge 90+"
check_item "Mobile - iOS Safari"
check_item "Mobile - Chrome Android"
check_item "Mobile - Samsung Internet"

echo ""
echo "⚡ PERFORMANCE"
echo "=============="
check_item "Page load time under 3 seconds"
check_item "Images optimized"
check_item "CSS and JS minified"
check_item "Critical rendering path optimized"
check_item "Mobile PageSpeed score 80+"

echo ""
echo "🎯 BUSINESS SETUP"
echo "================="
check_item "Business email address active"
check_item "Email monitored daily"
check_item "Response plan for inquiries documented"
check_item "Inquiry response template created"
check_item "Payment processing setup"
check_item "Accounting for payments configured"
check_item "Customer support procedure established"

echo ""
echo "📋 DOCUMENTATION"
echo "================"
check_item "Setup guide saved and backed up"
check_item "Credentials documented securely"
check_item "Deployment instructions saved"
check_item "Emergency contacts listed"
check_item "Backup procedures established"

echo ""
echo "=============================================="
echo "✅ Pre-Launch Checklist Complete!"
echo "🎉 Your website is ready to go live!"
echo "=============================================="
echo ""
echo "Next steps:"
echo "1. Deploy to live hosting"
echo "2. Update DNS records"
echo "3. Test live website"
echo "4. Monitor analytics"
echo "5. Start marketing!"
echo ""
echo "Questions? Check SETUP.md or DEPLOYMENT.md"
